// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApvJrNEmeqAn-CtFHOV-BZNhlRoA2cJJI',
    appId: '1:923059500041:web:b7976ed583186e976cb4d8',
    messagingSenderId: '923059500041',
    projectId: 'learnapplication-f2c26',
    authDomain: 'learnapplication-f2c26.firebaseapp.com',
    storageBucket: 'learnapplication-f2c26.appspot.com',
    measurementId: 'G-HVBZJ5H55M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5nh_EcoNtOYOjVuAfUnuyGVSd_VnHnXU',
    appId: '1:923059500041:android:d8b012db5d05a5046cb4d8',
    messagingSenderId: '923059500041',
    projectId: 'learnapplication-f2c26',
    storageBucket: 'learnapplication-f2c26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFF2qJh7-m06zjik4B9VpflRkPBg2fn8I',
    appId: '1:923059500041:ios:81b34368373bee576cb4d8',
    messagingSenderId: '923059500041',
    projectId: 'learnapplication-f2c26',
    storageBucket: 'learnapplication-f2c26.appspot.com',
    iosBundleId: 'com.example.flutterApplicationTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFF2qJh7-m06zjik4B9VpflRkPBg2fn8I',
    appId: '1:923059500041:ios:aac57a8f345c8d776cb4d8',
    messagingSenderId: '923059500041',
    projectId: 'learnapplication-f2c26',
    storageBucket: 'learnapplication-f2c26.appspot.com',
    iosBundleId: 'com.example.flutterApplicationTest1.RunnerTests',
  );
}
